version: '3.1'

services:
  postgresdb:
    image: postgres:11
    container_name: gurukulams_notebook_db
    environment:
      POSTGRES_DB: gurukulams_notebook_db
      POSTGRES_USER: tom
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"