name: Dev Build

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build the Infrastructure
      run: docker-compose up -d
    - name: Prepare Code
      run: |
        ./mvnw -s $GITHUB_WORKSPACE/src/main/res/.m2/settings.xml -B clean package -DskipTests --file pom.xml
        ./mvnw -s $GITHUB_WORKSPACE/src/main/res/.m2/settings.xml -B exec:java --file pom.xml
      env:
        USER_NAME: ${{ secrets.GH_PACKAGE_USER }}
        ACCESS_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}
    - name: Move the Artifacts
      run: cp -rf target/generated-sources/notebook/* src/main/java && rm -rf target/generated-sources && ls target && sed -i '/<!--Compiler/,/End-->/d' pom.xml
    - name: Quality Check
      run: ./mvnw -s $GITHUB_WORKSPACE/src/main/res/.m2/settings.xml -B -Dcheckstyle.skip jacoco:prepare-agent install jacoco:report --file pom.xml
      env:
        USER_NAME: ${{ secrets.GH_PACKAGE_USER }}
        ACCESS_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
