# This workflow will build a package then publish to GitHub Maven Access controlled repository

name: Release

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Build the Infrastructure
        run: docker compose up -d
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Build
        run: |
          ./mvnw --quiet -s $GITHUB_WORKSPACE/src/main/res/.m2/settings.xml -B clean package -DskipTests --file pom.xml
          ./mvnw --quiet -s $GITHUB_WORKSPACE/src/main/res/.m2/settings.xml -B exec:java --file pom.xml
        env:
          USER_NAME: ${{ secrets.GH_PACKAGE_USER }}
          ACCESS_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}
      - name: Move the Artifacts
        run: cp -rf target/generated-sources/notebook/* src/main/java && rm -rf target/generated-sources && ls target && sed -i '/<!--Compiler/,/End-->/d' pom.xml
      - name: Publish to GitHub Maven Repository
        run: ./mvnw -DskipTests -Dcheckstyle.skip deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
